# Form implementation generated from reading ui file 'QLnguoidung.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(parent=UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupbox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupbox.setObjectName("groupbox")
        self.gridlayout = QtWidgets.QGridLayout(self.groupbox)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(parent=self.groupbox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtUserID = QtWidgets.QLineEdit(parent=self.groupbox)
        self.txtUserID.setObjectName("txtUserID")
        self.gridlayout.addWidget(self.txtUserID, 0, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(parent=self.groupbox)
        self.label1.setObjectName("label1")
        self.gridlayout.addWidget(self.label1, 0, 2, 1, 1)
        self.txtHoTen = QtWidgets.QLineEdit(parent=self.groupbox)
        self.txtHoTen.setObjectName("txtHoTen")
        self.gridlayout.addWidget(self.txtHoTen, 0, 3, 1, 1)
        self.label2 = QtWidgets.QLabel(parent=self.groupbox)
        self.label2.setObjectName("label2")
        self.gridlayout.addWidget(self.label2, 1, 0, 1, 1)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.groupbox)
        self.txtUsername.setObjectName("txtUsername")
        self.gridlayout.addWidget(self.txtUsername, 1, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(parent=self.groupbox)
        self.label3.setObjectName("label3")
        self.gridlayout.addWidget(self.label3, 1, 2, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.groupbox)
        self.txtPassword.setObjectName("txtPassword")
        self.gridlayout.addWidget(self.txtPassword, 1, 3, 1, 1)
        self.label4 = QtWidgets.QLabel(parent=self.groupbox)
        self.label4.setObjectName("label4")
        self.gridlayout.addWidget(self.label4, 2, 0, 1, 1)
        self.cbRole = QtWidgets.QComboBox(parent=self.groupbox)
        self.cbRole.setObjectName("cbRole")
        self.cbRole.addItem("")
        self.cbRole.addItem("")
        self.gridlayout.addWidget(self.cbRole, 2, 1, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(parent=self.groupbox)
        self.btnAdd.setObjectName("btnAdd")
        self.gridlayout.addWidget(self.btnAdd, 3, 0, 1, 1)
        self.btnUpdate = QtWidgets.QPushButton(parent=self.groupbox)
        self.btnUpdate.setObjectName("btnUpdate")
        self.gridlayout.addWidget(self.btnUpdate, 3, 1, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(parent=self.groupbox)
        self.btnDelete.setObjectName("btnDelete")
        self.gridlayout.addWidget(self.btnDelete, 3, 2, 1, 1)
        self.btnClear = QtWidgets.QPushButton(parent=self.groupbox)
        self.btnClear.setObjectName("btnClear")
        self.gridlayout.addWidget(self.btnClear, 3, 3, 1, 1)
        self.vboxlayout.addWidget(self.groupbox)
        self.tableUsers = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableUsers.setObjectName("tableUsers")
        self.tableUsers.setColumnCount(0)
        self.tableUsers.setRowCount(0)
        self.vboxlayout.addWidget(self.tableUsers)
        UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "Quản lý người dùng"))
        self.groupbox.setTitle(_translate("UserWindow", "Thông tin người dùng"))
        self.label.setText(_translate("UserWindow", "Mã người dùng"))
        self.label1.setText(_translate("UserWindow", "Họ tên"))
        self.label2.setText(_translate("UserWindow", "Tài khoản"))
        self.label3.setText(_translate("UserWindow", "Mật khẩu"))
        self.label4.setText(_translate("UserWindow", "Vai trò"))
        self.cbRole.setItemText(0, _translate("UserWindow", "Admin"))
        self.cbRole.setItemText(1, _translate("UserWindow", "Thủ thư"))
        self.btnAdd.setText(_translate("UserWindow", "Thêm"))
        self.btnUpdate.setText(_translate("UserWindow", "Sửa"))
        self.btnDelete.setText(_translate("UserWindow", "Xóa"))
        self.btnClear.setText(_translate("UserWindow", "Làm mới"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserWindow = QtWidgets.QMainWindow()
    ui = Ui_UserWindow()
    ui.setupUi(UserWindow)
    UserWindow.show()
    sys.exit(app.exec())
