# Form implementation generated from reading ui file 'QuanLySach.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 457)
        MainWindow.setStyleSheet("\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color: #f0f0f0;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 30, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lvQuanLySach = QtWidgets.QListView(parent=self.centralwidget)
        self.lvQuanLySach.setGeometry(QtCore.QRect(30, 60, 531, 291))
        self.lvQuanLySach.setObjectName("lvQuanLySach")
        self.btnThemSach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThemSach.setGeometry(QtCore.QRect(30, 360, 75, 31))
        self.btnThemSach.setObjectName("btnThemSach")
        self.btnSuaSach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSuaSach.setGeometry(QtCore.QRect(140, 360, 75, 31))
        self.btnSuaSach.setObjectName("btnSuaSach")
        self.btnXoaSach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoaSach.setGeometry(QtCore.QRect(250, 360, 75, 31))
        self.btnXoaSach.setObjectName("btnXoaSach")
        self.btnTimkiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTimkiem.setGeometry(QtCore.QRect(360, 360, 75, 31))
        self.btnTimkiem.setObjectName("btnTimkiem")
        self.txtTimKiem = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtTimKiem.setGeometry(QtCore.QRect(440, 360, 104, 31))
        self.txtTimKiem.setObjectName("txtTimKiem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Quản lý Sách"))
        self.btnThemSach.setText(_translate("MainWindow", "Thêm"))
        self.btnSuaSach.setText(_translate("MainWindow", "Sửa"))
        self.btnXoaSach.setText(_translate("MainWindow", "Xóa"))
        self.btnTimkiem.setText(_translate("MainWindow", "Tìm kiếm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
