# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, SearchWindow):
        SearchWindow.setObjectName("SearchWindow")
        SearchWindow.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=SearchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtKeyword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtKeyword.setObjectName("txtKeyword")
        self.gridlayout.addWidget(self.txtKeyword, 0, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(parent=self.groupBox)
        self.label1.setObjectName("label1")
        self.gridlayout.addWidget(self.label1, 1, 0, 1, 1)
        self.radioMaSach = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioMaSach.setObjectName("radioMaSach")
        self.gridlayout.addWidget(self.radioMaSach, 1, 1, 1, 1)
        self.radioTenSach = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioTenSach.setObjectName("radioTenSach")
        self.gridlayout.addWidget(self.radioTenSach, 1, 2, 1, 1)
        self.radioTacGia = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioTacGia.setObjectName("radioTacGia")
        self.gridlayout.addWidget(self.radioTacGia, 2, 1, 1, 1)
        self.radioTheLoai = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioTheLoai.setObjectName("radioTheLoai")
        self.gridlayout.addWidget(self.radioTheLoai, 2, 2, 1, 1)
        self.label2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label2.setObjectName("label2")
        self.gridlayout.addWidget(self.label2, 3, 0, 1, 1)
        self.cbTrangThai = QtWidgets.QComboBox(parent=self.groupBox)
        self.cbTrangThai.setObjectName("cbTrangThai")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.gridlayout.addWidget(self.cbTrangThai, 3, 1, 1, 1)
        self.btnSearch = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnSearch.setObjectName("btnSearch")
        self.gridlayout.addWidget(self.btnSearch, 4, 1, 1, 1)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridlayout.addWidget(self.btnRefresh, 4, 2, 1, 1)
        self.vboxlayout.addWidget(self.groupBox)
        self.tableSearch = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableSearch.setObjectName("tableSearch")
        self.tableSearch.setColumnCount(0)
        self.tableSearch.setRowCount(0)
        self.vboxlayout.addWidget(self.tableSearch)
        SearchWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SearchWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchWindow)

    def retranslateUi(self, SearchWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchWindow.setWindowTitle(_translate("MainWindow", "Tìm kiếm sách"))
        self.groupBox.setTitle(_translate("MainWindow", "Tìm kiếm"))
        self.label.setText(_translate("MainWindow", "Từ khóa"))
        self.label1.setText(_translate("MainWindow", "Tìm theo"))
        self.radioMaSach.setText(_translate("MainWindow", "Mã sách"))
        self.radioTenSach.setText(_translate("MainWindow", "Tên sách"))
        self.radioTacGia.setText(_translate("MainWindow", "Tác giả"))
        self.radioTheLoai.setText(_translate("MainWindow", "Thể loại"))
        self.label2.setText(_translate("MainWindow", "Trạng thái"))
        self.cbTrangThai.setItemText(0, _translate("MainWindow", "Tất cả"))
        self.cbTrangThai.setItemText(1, _translate("MainWindow", "Còn sách"))
        self.cbTrangThai.setItemText(2, _translate("MainWindow", "Đang mượn"))
        self.btnSearch.setText(_translate("MainWindow", "Tìm kiếm"))
        self.btnRefresh.setText(_translate("MainWindow", "Làm mới"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(SearchWindow)
    SearchWindow.show()
    sys.exit(app.exec())
