# Form implementation generated from reading ui file 'thongke.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThongKeWindow(object):
    def setupUi(self, ThongKeWindow):
        ThongKeWindow.setObjectName("ThongKeWindow")
        ThongKeWindow.resize(900, 595)
        self.centralwidget = QtWidgets.QWidget(parent=ThongKeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateFrom = QtWidgets.QDateEdit(parent=self.groupBox)
        self.dateFrom.setObjectName("dateFrom")
        self.gridlayout.addWidget(self.dateFrom, 0, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(parent=self.groupBox)
        self.label1.setObjectName("label1")
        self.gridlayout.addWidget(self.label1, 0, 2, 1, 1)
        self.dateTo = QtWidgets.QDateEdit(parent=self.groupBox)
        self.dateTo.setObjectName("dateTo")
        self.gridlayout.addWidget(self.dateTo, 0, 3, 1, 1)
        self.btnThongKe = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnThongKe.setObjectName("btnThongKe")
        self.gridlayout.addWidget(self.btnThongKe, 1, 1, 1, 1)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox1.setObjectName("groupBox1")
        self.gridlayout1 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label2 = QtWidgets.QLabel(parent=self.groupBox1)
        self.label2.setObjectName("label2")
        self.gridlayout1.addWidget(self.label2, 0, 0, 1, 1)
        self.txtTongSach = QtWidgets.QLineEdit(parent=self.groupBox1)
        self.txtTongSach.setObjectName("txtTongSach")
        self.gridlayout1.addWidget(self.txtTongSach, 0, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(parent=self.groupBox1)
        self.label3.setObjectName("label3")
        self.gridlayout1.addWidget(self.label3, 0, 2, 1, 1)
        self.txtDangMuon = QtWidgets.QLineEdit(parent=self.groupBox1)
        self.txtDangMuon.setObjectName("txtDangMuon")
        self.gridlayout1.addWidget(self.txtDangMuon, 0, 3, 1, 1)
        self.label4 = QtWidgets.QLabel(parent=self.groupBox1)
        self.label4.setObjectName("label4")
        self.gridlayout1.addWidget(self.label4, 1, 0, 1, 1)
        self.txtQuaHan = QtWidgets.QLineEdit(parent=self.groupBox1)
        self.txtQuaHan.setObjectName("txtQuaHan")
        self.gridlayout1.addWidget(self.txtQuaHan, 1, 1, 1, 1)
        self.label5 = QtWidgets.QLabel(parent=self.groupBox1)
        self.label5.setObjectName("label5")
        self.gridlayout1.addWidget(self.label5, 1, 2, 1, 1)
        self.txtTongPhat = QtWidgets.QLineEdit(parent=self.groupBox1)
        self.txtTongPhat.setObjectName("txtTongPhat")
        self.gridlayout1.addWidget(self.txtTongPhat, 1, 3, 1, 1)
        self.vboxlayout.addWidget(self.groupBox1)
        self.tableThongKe = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableThongKe.setObjectName("tableThongKe")
        self.tableThongKe.setColumnCount(0)
        self.tableThongKe.setRowCount(0)
        self.vboxlayout.addWidget(self.tableThongKe)
        ThongKeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ThongKeWindow)
        QtCore.QMetaObject.connectSlotsByName(ThongKeWindow)

    def retranslateUi(self, ThongKeWindow):
        _translate = QtCore.QCoreApplication.translate
        ThongKeWindow.setWindowTitle(_translate("ThongKeWindow", "Thống kê thư viện"))
        self.groupBox.setTitle(_translate("ThongKeWindow", "Bộ lọc thống kê"))
        self.label.setText(_translate("ThongKeWindow", "Từ ngày"))
        self.label1.setText(_translate("ThongKeWindow", "Đến ngày"))
        self.btnThongKe.setText(_translate("ThongKeWindow", "Thống kê"))
        self.groupBox1.setTitle(_translate("ThongKeWindow", "Kết quả thống kê"))
        self.label2.setText(_translate("ThongKeWindow", "Tổng sách"))
        self.label3.setText(_translate("ThongKeWindow", "Sách đang mượn"))
        self.label4.setText(_translate("ThongKeWindow", "Sách quá hạn"))
        self.label5.setText(_translate("ThongKeWindow", "Tổng tiền phạt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThongKeWindow = QtWidgets.QMainWindow()
    ui = Ui_ThongKeWindow()
    ui.setupUi(ThongKeWindow)
    ThongKeWindow.show()
    sys.exit(app.exec())
