
# Form implementation generated from reading ui file 'UIDangNhap.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(420, 376)
        self.vboxlayout = QtWidgets.QVBoxLayout(LoginForm)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(parent=LoginForm)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.txtUser = QtWidgets.QLineEdit(parent=LoginForm)
        self.txtUser.setObjectName("txtUser")
        self.vboxlayout.addWidget(self.txtUser)
        self.txtPass = QtWidgets.QLineEdit(parent=LoginForm)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPass.setObjectName("txtPass")
        self.vboxlayout.addWidget(self.txtPass)
        self.btnLogin = QtWidgets.QPushButton(parent=LoginForm)
        self.btnLogin.setObjectName("btnLogin")
        self.vboxlayout.addWidget(self.btnLogin)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Hệ Thống Thư Viện - Đăng nhập"))
        self.label.setStyleSheet(_translate("LoginForm", "font-size:15px;font-weight:bold"))
        self.label.setText(_translate("LoginForm", "ĐĂNG NHẬP HỆ THỐNG"))
        self.txtUser.setPlaceholderText(_translate("LoginForm", "Tên đăng nhập"))
        self.txtPass.setPlaceholderText(_translate("LoginForm", "Mật khẩu"))
        self.btnLogin.setStyleSheet(_translate("LoginForm", "font-size:14px;font-weight:bold"))
        self.btnLogin.setText(_translate("LoginForm", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(LoginForm)
    LoginForm.show()
    sys.exit(app.exec())
