# Form implementation generated from reading ui file 'UIDangKy.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(420, 420)
        self.vboxlayout = QtWidgets.QVBoxLayout(RegisterForm)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(parent=RegisterForm)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.txtUser = QtWidgets.QLineEdit(parent=RegisterForm)
        self.txtUser.setMinimumHeight(40)
        self.txtUser.setObjectName("txtUser")
        self.vboxlayout.addWidget(self.txtUser)
        self.txtPass = QtWidgets.QLineEdit(parent=RegisterForm)
        self.txtPass.setMinimumHeight(40)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPass.setObjectName("txtPass")
        self.vboxlayout.addWidget(self.txtPass)
        self.cboRole = QtWidgets.QComboBox(parent=RegisterForm)
        self.cboRole.setMinimumHeight(40)
        self.cboRole.setObjectName("cboRole")
        self.cboRole.addItem("")
        self.vboxlayout.addWidget(self.cboRole)
        self.btnCreate = QtWidgets.QPushButton(parent=RegisterForm)
        self.btnCreate.setMinimumHeight(45)
        self.btnCreate.setObjectName("btnCreate")
        self.vboxlayout.addWidget(self.btnCreate)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Đăng ký tài khoản"))
        self.label.setText(_translate("RegisterForm", "ĐĂNG KÝ TÀI KHOẢN"))
        self.label.setStyleSheet(_translate("RegisterForm", "font-size:14px;font-weight:bold"))
        self.txtUser.setPlaceholderText(_translate("RegisterForm", "Tên đăng nhập"))
        self.txtPass.setPlaceholderText(_translate("RegisterForm", "Mật khẩu"))
        self.cboRole.setItemText(0, _translate("RegisterForm", "NhanVien"))
        self.btnCreate.setStyleSheet(_translate("RegisterForm", "font-weight:bold"))
        self.btnCreate.setText(_translate("RegisterForm", "Tạo tài khoản"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterForm = QtWidgets.QWidget()
    ui = Ui_RegisterForm()
    ui.setupUi(RegisterForm)
    RegisterForm.show()
    sys.exit(app.exec())
