# Form implementation generated from reading ui file 'UITaiKhoan.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 650)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setObjectName("frame")
        self.gridlayout = QtWidgets.QGridLayout(self.frame)
        self.gridlayout.setObjectName("gridlayout")
        self.label1 = QtWidgets.QLabel(parent=self.frame)
        self.label1.setObjectName("label1")
        self.gridlayout.addWidget(self.label1, 0, 0, 1, 1)
        self.txt_username = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_username.setObjectName("txt_username")
        self.gridlayout.addWidget(self.txt_username, 0, 1, 1, 1)
        self.label2 = QtWidgets.QLabel(parent=self.frame)
        self.label2.setObjectName("label2")
        self.gridlayout.addWidget(self.label2, 1, 0, 1, 1)
        self.txt_password = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.gridlayout.addWidget(self.txt_password, 1, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(parent=self.frame)
        self.label3.setObjectName("label3")
        self.gridlayout.addWidget(self.label3, 2, 0, 1, 1)
        self.cb_role = QtWidgets.QComboBox(parent=self.frame)
        self.cb_role.setObjectName("cb_role")
        self.cb_role.addItem("")
        self.cb_role.addItem("")
        self.gridlayout.addWidget(self.cb_role, 2, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(parent=self.frame)
        self.label4.setObjectName("label4")
        self.gridlayout.addWidget(self.label4, 3, 0, 1, 1)
        self.cb_status = QtWidgets.QComboBox(parent=self.frame)
        self.cb_status.setObjectName("cb_status")
        self.cb_status.addItem("")
        self.cb_status.addItem("")
        self.gridlayout.addWidget(self.cb_status, 3, 1, 1, 1)
        self.vboxlayout.addWidget(self.frame)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.btn_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.hboxlayout.addWidget(self.btn_add)
        self.btn_update = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_update.setObjectName("btn_update")
        self.hboxlayout.addWidget(self.btn_update)
        self.btn_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_delete.setObjectName("btn_delete")
        self.hboxlayout.addWidget(self.btn_delete)
        self.btn_refresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.hboxlayout.addWidget(self.btn_refresh)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.table_accounts = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_accounts.setObjectName("table_accounts")
        self.table_accounts.setColumnCount(3)
        self.table_accounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_accounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_accounts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_accounts.setHorizontalHeaderItem(2, item)
        self.vboxlayout.addWidget(self.table_accounts)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản lý tài khoản"))
        self.label.setText(_translate("MainWindow", "QUẢN LÝ TÀI KHOẢN"))
        self.label.setStyleSheet(_translate("MainWindow", "font-size:22px; font-weight:bold;"))
        self.frame.setStyleSheet(_translate("MainWindow", "\n"
"        background:white;\n"
"        border-radius:10px;\n"
"        border:1px solid #ccc;\n"
"       "))
        self.label1.setText(_translate("MainWindow", "Tên đăng nhập:"))
        self.label2.setText(_translate("MainWindow", "Mật khẩu:"))
        self.label3.setText(_translate("MainWindow", "Vai trò:"))
        self.cb_role.setItemText(0, _translate("MainWindow", "Admin"))
        self.cb_role.setItemText(1, _translate("MainWindow", "Nhân viên"))
        self.label4.setText(_translate("MainWindow", "Trạng thái:"))
        self.cb_status.setItemText(0, _translate("MainWindow", "Hoạt động"))
        self.cb_status.setItemText(1, _translate("MainWindow", "Khóa"))
        self.btn_add.setText(_translate("MainWindow", "Thêm"))
        self.btn_add.setStyleSheet(_translate("MainWindow", "background:#2ecc71; color:white;"))
        self.btn_update.setText(_translate("MainWindow", "Sửa"))
        self.btn_update.setStyleSheet(_translate("MainWindow", "background:#3498db; color:white;"))
        self.btn_delete.setText(_translate("MainWindow", "Xóa"))
        self.btn_delete.setStyleSheet(_translate("MainWindow", "background:#e74c3c; color:white;"))
        self.btn_refresh.setText(_translate("MainWindow", "Làm mới"))
        item = self.table_accounts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.table_accounts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vai trò"))
        item = self.table_accounts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Trạng thái"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
