# Form implementation generated from reading ui file 'UIThongKE.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.sidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebar.setMinimumWidth(250)
        self.sidebar.setObjectName("sidebar")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(parent=self.sidebar)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.pushbutton = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton.setObjectName("pushbutton")
        self.vboxlayout.addWidget(self.pushbutton)
        self.pushbutton1 = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton1.setObjectName("pushbutton1")
        self.vboxlayout.addWidget(self.pushbutton1)
        self.pushbutton2 = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton2.setObjectName("pushbutton2")
        self.vboxlayout.addWidget(self.pushbutton2)
        self.pushbutton3 = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton3.setObjectName("pushbutton3")
        self.vboxlayout.addWidget(self.pushbutton3)
        self.pushbutton4 = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton4.setObjectName("pushbutton4")
        self.vboxlayout.addWidget(self.pushbutton4)
        self.pushbutton5 = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton5.setObjectName("pushbutton5")
        self.vboxlayout.addWidget(self.pushbutton5)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.pushbutton6 = QtWidgets.QPushButton(parent=self.sidebar)
        self.pushbutton6.setObjectName("pushbutton6")
        self.vboxlayout.addWidget(self.pushbutton6)
        self.hboxlayout.addWidget(self.sidebar)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setObjectName("frame")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.frame)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label1 = QtWidgets.QLabel(parent=self.frame)
        self.label1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label1.setObjectName("label1")
        self.vboxlayout1.addWidget(self.label1)
        self.vboxlayout2 = QtWidgets.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.barFrame = QtWidgets.QFrame(parent=self.frame)
        self.barFrame.setMinimumHeight(250)
        self.barFrame.setObjectName("barFrame")
        self.vboxlayout2.addWidget(self.barFrame)
        self.pieFrame = QtWidgets.QFrame(parent=self.frame)
        self.pieFrame.setMinimumHeight(250)
        self.pieFrame.setObjectName("pieFrame")
        self.vboxlayout2.addWidget(self.pieFrame)
        self.vboxlayout1.addLayout(self.vboxlayout2)
        self.hboxlayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HỆ THỐNG QUẢN LÝ THƯ VIỆN"))
        self.sidebar.setStyleSheet(_translate("MainWindow", "\n"
"        background:#2c3e50;\n"
"        color:white;\n"
"       "))
        self.label.setText(_translate("MainWindow", "LIBRARY PRO"))
        self.label.setStyleSheet(_translate("MainWindow", "font-size:20px; font-weight:bold;"))
        self.pushbutton.setText(_translate("MainWindow", "Trang chủ"))
        self.pushbutton1.setText(_translate("MainWindow", "Báo cáo thống kê"))
        self.pushbutton2.setText(_translate("MainWindow", "Quản lý sách"))
        self.pushbutton3.setText(_translate("MainWindow", "Mượn & Trả"))
        self.pushbutton4.setText(_translate("MainWindow", "Nhập hàng"))
        self.pushbutton5.setText(_translate("MainWindow", "Nhà cung cấp"))
        self.pushbutton6.setText(_translate("MainWindow", "Thoát"))
        self.pushbutton6.setStyleSheet(_translate("MainWindow", "\n"
"           background:#e74c3c;\n"
"           color:white;\n"
"           font-weight:bold;\n"
"          "))
        self.frame.setStyleSheet(_translate("MainWindow", "background:#ecf0f1;"))
        self.label1.setText(_translate("MainWindow", "BÁO CÁO THỐNG KÊ CHI TIẾT"))
        self.label1.setStyleSheet(_translate("MainWindow", "font-size:22px; font-weight:bold;"))
        self.barFrame.setStyleSheet(_translate("MainWindow", "\n"
"             background:white;\n"
"             border-radius:10px;\n"
"             border:1px solid #ccc;\n"
"            "))
        self.pieFrame.setStyleSheet(_translate("MainWindow", "\n"
"             background:white;\n"
"             border-radius:10px;\n"
"             border:1px solid #ccc;\n"
"            "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
