# Form implementation generated from reading ui file 'UITrangChu.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)

        self.hboxlayout = QtWidgets.QHBoxLayout(self.centralwidget)

        # ================= SIDEBAR =================
        self.sidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(220, 0))
        self.sidebar.setStyleSheet("background-color:#2c3e50;color:white;")

        self.vboxlayout = QtWidgets.QVBoxLayout(self.sidebar)

        self.label = QtWidgets.QLabel("LIBRARY PRO")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setStyleSheet("font-size:20px;font-weight:bold;padding:20px")
        self.vboxlayout.addWidget(self.label)

        self.btnTrangChu = QtWidgets.QPushButton("Trang chủ")
        self.btnTrangChu.setMinimumHeight(45)
        self.btnTrangChu.setStyleSheet("background:#3498db;border-radius:8px;")
        self.vboxlayout.addWidget(self.btnTrangChu)

        self.btnSach = QtWidgets.QPushButton("Quản lý Sách")
        self.btnSach.setMinimumHeight(45)
        self.vboxlayout.addWidget(self.btnSach)

        self.btnMuonTra = QtWidgets.QPushButton("Mượn & Trả")
        self.btnMuonTra.setMinimumHeight(45)
        self.vboxlayout.addWidget(self.btnMuonTra)

        self.btnNhap = QtWidgets.QPushButton("Nhập hàng")
        self.btnNhap.setMinimumHeight(45)
        self.vboxlayout.addWidget(self.btnNhap)

        self.btnNCC = QtWidgets.QPushButton("Nhà cung cấp")
        self.btnNCC.setMinimumHeight(45)
        self.vboxlayout.addWidget(self.btnNCC)

        self.btnUser = QtWidgets.QPushButton("Tài khoản")
        self.btnUser.setMinimumHeight(45)
        self.vboxlayout.addWidget(self.btnUser)

        # FIX SPACER
        spacerItem = QtWidgets.QSpacerItem(
            20, 40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.vboxlayout.addItem(spacerItem)

        self.btnLogout = QtWidgets.QPushButton("Đăng xuất")
        self.btnLogout.setMinimumHeight(45)
        self.btnLogout.setStyleSheet(
            "background:#e74c3c;border-radius:8px;color:white;"
        )
        self.vboxlayout.addWidget(self.btnLogout)

        self.hboxlayout.addWidget(self.sidebar)

        # ================= CONTENT =================
        self.content = QtWidgets.QFrame()
        self.content.setStyleSheet("background:#ecf0f1;border-radius:10px;")

        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.content)

        self.label1 = QtWidgets.QLabel("TRANG CHỦ")
        self.label1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label1.setStyleSheet("font-size:22px;font-weight:bold")
        self.vboxlayout1.addWidget(self.label1)

        # DASHBOARD
        self.dashboard = QtWidgets.QHBoxLayout()

        self.box1 = self.create_box("Tổng sách", "0")
        self.box2 = self.create_box("Đang mượn", "0")
        self.box3 = self.create_box("Quá hạn", "0")

        self.dashboard.addWidget(self.box1)
        self.dashboard.addWidget(self.box2)
        self.dashboard.addWidget(self.box3)

        self.vboxlayout1.addLayout(self.dashboard)

        # TABLE
        self.tableSach = QtWidgets.QTableWidget()
        self.tableSach.setColumnCount(4)
        self.tableSach.setHorizontalHeaderLabels(
            ["Mã sách", "Tên sách", "Tác giả", "Số lượng"]
        )
        self.vboxlayout1.addWidget(self.tableSach)

        self.hboxlayout.addWidget(self.content)

        MainWindow.setCentralWidget(self.centralwidget)

    # ================= DASHBOARD BOX =================
    def create_box(self, title, value):
        frame = QtWidgets.QFrame()
        frame.setStyleSheet(
            """
            background:white;
            border-radius:8px;
            padding:15px;
            """
        )

        layout = QtWidgets.QVBoxLayout(frame)

        lbl1 = QtWidgets.QLabel(title)
        lbl2 = QtWidgets.QLabel(value)

        lbl2.setStyleSheet("font-size:20px;font-weight:bold")

        layout.addWidget(lbl1)
        layout.addWidget(lbl2)

        return frame


# ================= RUN APP =================
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()

    sys.exit(app.exec())